blue_donut/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('planner/', include('route_planner.urls')),
    path('auth/', include('eve_auth.urls', namespace='eve_auth')),
    path('manager/', include('jump_bridges.urls')),
    path('admin/', admin.site.urls),
]

eve_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import eve_auth.views

app_name = 'eve_auth'

urlpatterns = [
    path('login/', eve_auth.views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('callback/', eve_auth.views.CallbackView.as_view(), name='callback'),
]

route_planner/urls.py
from django.urls import path
import route_planner.views


app_name = 'route_planner'


urlpatterns = [
    path('', route_planner.views.PlannerView.as_view(), name='planner'),
    path('report/', route_planner.views.ReportView.as_view(), name='report'),
]

route_planner/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings

from eve_esi import ESI
from eve_auth.models import EveUser

from route_planner.backend import RoutePlannerBackend

from dhooks import Webhook, Embed
hook = Webhook(settings.WEBHOOK_URL)


class PlannerView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'route_planner/planner.html')

    def post(self, request):
        try:
            character = request.user.characters.get(character_id=int(
                request.POST['character_id']
            ))
        except EveUser.DoesNotExist:
            return HttpResponse(status=403)

        req = ESI.request(
            'get_characters_character_id_location',
            client=character.get_client(),
            character_id=int(request.POST['character_id'])
        ).data.solar_system_id

        route = RoutePlannerBackend().generate(
            req,
            request.POST['destination']
        )

        if 'verify' in request.POST:
            return render(
                request,
                'route_planner/planner.html',
                {
                    'dotlan': route['dotlan'],
                    'destination': request.POST['destination'],
                    'jumps': route['length'],
                    'mapDisplay': True,
                    'confirmButton': True,
                }
            )
        elif 'confirm' in request.POST:
            for i in range(len(route['esi'])):
                if i == 0:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=True,
                        destination_id=route['esi'][i]
                    )
                else:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=False,
                        destination_id=route['esi'][i]
                    )
            return render(
                request,
                'route_planner/planner.html',
                {
                    'dotlan': route['dotlan'],
                    'destination': request.POST['destination'],
                    'jumps': route['length'],
                    'mapDisplay': True,
                    'confirmButton': False,
                }
            )
        elif 'generate' in request.POST:
            for i in range(len(route['esi'])):
                if i == 0:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=True,
                        destination_id=route['esi'][i]
                    )
                else:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=False,
                        destination_id=route['esi'][i]
                    )
            return render(
                request,
                'route_planner/planner.html',
                {
                    'dotlan': route['dotlan'],
                    'destination': request.POST['destination'],
                    'jumps': route['length'],
                    'mapDisplay': True,
                    'confirmButton': False,
                }
            )
        else:
            for i in range(len(route['esi'])):
                if i == 0:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=True,
                        destination_id=route['esi'][i]
                    )
                else:
                    ESI.request(
                        'post_ui_autopilot_waypoint',
                        client=character.get_client(),
                        add_to_beginning=False,
                        clear_other_waypoints=False,
                        destination_id=route['esi'][i]
                    )
            return render(
                request,
                'route_planner/planner.html',
                {
                    'jumps': route['length'],
                    'mapDisplay': False,
                    'confirmButton': False,
                }
            )


class ReportView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'route_planner/report.html')

    def post(self, request):
        try:
            character = request.user.characters.get(character_id=int(
                request.POST['characterID']
            ))
        except EveUser.DoesNotExist:
            return HttpResponse(status=403)

        reportSubmitter = ESI.request(
            'get_characters_character_id',
            client=character.get_client(),
            character_id=int(request.POST['characterID'])
        ).data.name

        embed = Embed(
            description='An Ansiblex Jump Gate outage has been reported.',
            color=0x375A7F,
            timestamp='now'
        )

        reportSubmitterIcon = "https://image.eveonline.com/Character/" + \
            request.POST['characterID'] + "_32.jpg"
        footerIcon = "https://bluedonut.space/static/img/favicon.png"

        embed.set_author(name=reportSubmitter, icon_url=reportSubmitterIcon)
        embed.add_field(name="From System", value=request.POST['fromSystem'])
        embed.add_field(name="To System", value=request.POST['toSystem'])
        embed.set_footer(text="Blue Donut", icon_url=footerIcon)

        if (request.POST['structureID']):
            embed.add_field(name="Structure ID",
                            value=request.POST['structureID'],
                            inline=False)

        hook.send(embed=embed)

        return redirect('/planner/')

route_planner/templates/route_planner/planner.html
{% extends 'content_page.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Route Planner{% endblock %}
{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="container-alt toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Route Planner</span>
            </h1>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h2 class="text-center"><i class="fas fa-bookmark mr-3"></i>Destinations</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="list-group">
                        <input type="submit" class="list-group-item list-group-item-action" value="D-PNP9" onclick="buttonClick('D-PNP9');">
                        <input type="submit" class="list-group-item list-group-item-action" value="GE-8JV" onclick="buttonClick('GE-8JV');">
                        <input type="submit" class="list-group-item list-group-item-action" value="PZMA-E" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item-action" value="U-QVWD" onclick="buttonClick('U-QVWD');">
                        <input type="submit" class="list-group-item list-group-item-action" value="6E-MOW" onclick="buttonClick('6E-MOW');">
                    </div>
                    <small class="form-text text-muted mt-2">Popular</small>
                </div>
                <div class="col-md-4">
                    <div class="list-group">
                        <input type="submit" class="list-group-item list-group-item disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                    </div>
                    <small class="form-text text-muted mt-2">Favorites</small>
                </div>
                <div class="col-md-4">
                    <div class="list-group">
                        <input type="submit" class="list-group-item list-group-item- disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item- disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item- disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item- disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                        <input type="submit" class="list-group-item list-group-item- disabled" value="N/A" onclick="buttonClick('PZMA-E');">
                    </div>
                    <small class="form-text text-muted mt-2">Recent</small>
                </div>
            </div>
            <div class="row justify-content-center">
                <p class="mt-2">Favorites and recents are still a work in progress.</p>
            </div>
        </div>
        <div class="col-md-6">
            <h2 class="text-center"><i class="fas fa-pen mr-3"></i>Create Your Own</h2>
            <form id="destinationForm" action="/planner/" method="post">
                {% csrf_token %}
                <div class="form-row mb-1">
                    <div id="prefetch" class="col-6">
                        <input type="text" id="destinationInput" name="destination" class="form-control typeahead" placeholder="Destination" autocomplete="off" required>
                    </div>
                    <div class="col-3">
                        <input type="submit" id="destinationVerify" name="verify" value="Verify" class="btn btn-block btn-primary" onclick="document.getElementById('character_id').value = get_active_character();">
                    </div>
                    <div class="col-3">
                        <input type="submit" id="destinationSubmit" name="generate" value="Generate" class="btn btn-block btn-primary" onclick="document.getElementById('character_id').value = get_active_character();">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <small class="form-text text-muted mt-0">
                        Please only input correct system names.
                        </small>
                        <small class="form-text text-muted mt-0">
                        <a href="{% url 'route_planner:report' %}" class="text-info">
                        Report an incorrect jump bridge.
                        </a>
                        </small>
                    </div>
                    <input type="hidden" id="character_id" name="character_id" value="">
                </div>
            </form>
        </div>
    </div>
    {% if mapDisplay %}
    <div class="row justify-content-center">
        <div class="col-6">
            <object id="map" class="rounded" width="100%" data="https://freeburn.xyz/map/?&path={{ dotlan }}" type="image/svg+xml">
            </object>
        </div>
        <div class="col-2 text-center">
            <h2 class="mb-0">{{ destination|default:"No Destination Set" }}</h2>
            <p class="text-muted mb-2">{{ jumps|default:"No destination set." }} Jumps</p>
            {% if confirmButton %}
            <form id="confirmForm" action="/planner/" method="post">
                {% csrf_token %}
                <input type="hidden" id="destinationButton" name="destination" value="{{ destination }}">
                <input type="hidden" id="character_id_confirm" name="character_id" value="">
                <input type="submit" id="destinationConfirm" class="mr-3 btn btn-primary btn-block" name="confirm" value="Set destination" onclick="document.getElementById('character_id_confirm').value = get_active_character();">
            {% endif %}
            </form>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}
{% block trailing_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.2.1/typeahead.bundle.min.js"></script>
<script>
    $(document).ready(function(){
       $(".active").removeClass("active");
       $("#route_planner").addClass("active");
    });
    
    function buttonClick(button) {
        document.getElementById('destinationInput').value = button;
        document.getElementById("character_id").value = get_active_character();
        document.getElementById('destinationForm').submit();
    }
    
    var systems = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.whitespace,
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      // url points to a json file that contains an array of country names, see
      // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
      prefetch: '../static/json/systems.json'
    });
    
    // passing in `null` for the `options` arguments will result in the default
    // options being used
    var $typeahead = $('#prefetch .typeahead').typeahead(null, {
      name: 'systems',
      source: systems
    });
    
    var selected      = null;
    var originalVal   = null;
    
    // When the typeahead becomes active reset these values.
    $typeahead.on("typeahead:active", function(aEvent) {
       selected       = null;
       originalVal    = $typeahead.typeahead("val");
    })
    
    // When a suggestion gets selected save that
    $typeahead.on("typeahead:select", function(aEvent, aSuggestion) {
       selected = aSuggestion;
    });
    
    // Once user leaves the component and a change was registered
    // check whether or not something was selected. If not reset to
    // the original value.
    $typeahead.on("typeahead:change", function(aEvent, aSuggestion) {
       if (!selected) {
          $typeahead.typeahead("val", originalVal);
       }
    
       // Do something with the selected value here as needed...
    });   
</script>
{% endblock %}

route_planner/templates/route_planner/report.html
{% extends 'content_page.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Report{% endblock %}
{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="container-alt toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Report</span>
            </h1>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form id="reportForm" action="/planner/report/" method="post">
                {% csrf_token %}
                <div class="form-row" id="prefetch">
                    <div class="col text-center">
                        <label for="fromSystem">From</label><br>
                        <input type="text" id="fromSystem" name="fromSystem" class="form-control typeahead text-center" placeholder="System" required>
                    </div>
                    <div class="col text-center">
                        <label for="toSystem">To</label><br>
                        <input type="text" id="toSystem" name="toSystem" class="form-control typeahead text-center" placeholder="System" required>
                    </div>
                </div>
                <br>
                <div class="form-row">
                    <p>If you would like to provide additional information about the missing/incorrect jump gate, please follow these instructions:</p>
                    <ol>
                        <li>Open up the <a class="text-info" href="https://i.imgur.com/8THEffw.png">info panel</a> on the system with the incorrect gate.</li>
                        <li>Go to the <a class="text-info" href="https://i.imgur.com/2DI3pIb.png">Structures tab</a>.</li>
                        <li><a class="text-info" href="https://i.imgur.com/ci7K7xJ.png">Drag</a> the jump bridge structure (it's name contains the systems it links) to a chat window and send it.</li>
                        <li>Right click and <a class="text-info" href="https://i.imgur.com/lmocD4e.png">copy</a> the message.</li>
                        <li>Paste it into a notepad and take the <a class="text-info" href="https://i.imgur.com/mIR8gpa.png">long number</a>. This is the structure ID.</li>
                        <li>Put the structure ID in the input with the same label.</li>
                    </ol>
                    <p>As a note, it is common that if the structure ID is wrong but the system is right, when you go
                        to the system, the jump bridge will not be highlighted yellow. After you take the jump bridge,
                        your in-game route will tell you to go back to that system. This is because the structure was
                        picked up and moved, so the structure ID changed.
                    </p>
                    <input type="text" id="structureID" name="structureID" class="form-control mt-2" placeholder="Structure ID">
                </div>
                <div class="form-row justify-content-center">
                    <input type="hidden" id="characterID" name="characterID">
                    <input type="submit" id="reportSubmit" name="submit" value="Submit" class="btn btn-primary mb-2 mt-4 btn-lg" onclick="document.getElementById('characterID').value = get_active_character();">
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}
{% block trailing_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.2.1/typeahead.bundle.min.js"></script>
<script>
    $(document).ready(function(){
       $(".active").removeClass("active");
    });
    
    var systems = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.whitespace,
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      // url points to a json file that contains an array of country names, see
      // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
      prefetch: '../../static/json/systems.json'
    });
    
    // passing in `null` for the `options` arguments will result in the default
    // options being used
    var $typeahead = $('#prefetch .typeahead').typeahead(null, {
      name: 'systems',
      source: systems
    });
    
    var selected      = null;
    var originalVal   = null;
    
    // When the typeahead becomes active reset these values.
    $typeahead.on("typeahead:active", function(aEvent) {
       selected       = null;
       originalVal    = $typeahead.typeahead("val");
    })
    
    // When a suggestion gets selected save that
    $typeahead.on("typeahead:select", function(aEvent, aSuggestion) {
       selected = aSuggestion;
    });
    
    // Once user leaves the component and a change was registered
    // check whether or not something was selected. If not reset to
    // the original value.
    $typeahead.on("typeahead:change", function(aEvent, aSuggestion) {
       if (!selected) {
          $typeahead.typeahead("val", originalVal);
       }
    
       // Do something with the selected value here as needed...
    });   
</script>
{% endblock %}