blue_donut/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('planner/', include('route_planner.urls')),
    path('auth/', include('eve_auth.urls', namespace='eve_auth')),
    path('manager/', include('jump_bridges.urls')),
    path('admin/', admin.site.urls),
]

eve_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import eve_auth.views

app_name = 'eve_auth'

urlpatterns = [
    path('login/', eve_auth.views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('callback/', eve_auth.views.CallbackView.as_view(), name='callback'),
]

jump_bridges/urls.py
from django.urls import path
import jump_bridges.views


app_name = 'jump_bridges'

urlpatterns = [
    path('', jump_bridges.views.ManagerView.as_view(), name='manager'),
]

route_planner/urls.py
from django.urls import path
import route_planner.views


app_name = 'route_planner'


urlpatterns = [
    path('', route_planner.views.PlannerView.as_view(), name='planner'),
    path('report/', route_planner.views.ReportView.as_view(), name='report'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Easy-to-use route planner (and a few more features soon!) for Legacy Coalition.">
        <meta name="author" content="Aimsucks">
        <meta name="theme-color" content="#375A7F">
        <meta content="Blue Donut" property="og:author">
        <meta content="{% block title %}{% endblock %}" property="og:title">
        <meta content="Easy-to-use route planner (and a few more features soon!) for Legacy Coalition." property="og:description">
        <meta content="{% static 'img/favicon.png' %}" property='og:image'>
        <title>Blue Donut</title>
        {% block metadata %}{% endblock %}
        {% block extra_styling %}{% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}" />
        <script src="https://kit.fontawesome.com/59213b9e2d.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/darkly/bootstrap.min.css" />
        <link rel="stylesheet" href="{% static 'css/blue_donut.css' %}" />
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-primary">
            <div class="container">
                <ul class="navbar-nav navbar-fill">
                    <a class="navbar-brand" href="/">Blue Donut</a>
                    <li class="nav-item header-link" id="route_planner">
                        <a class="nav-link" href="{% url 'route_planner:planner' %}" role="button">
                        Route Planner
                        </a>
                    </li>
                    <li class="nav-item" id="scans">
                        <a class="nav-link disabled" href="#" role="button">
                        Scans
                        </a>
                    </li>
                    <li class="nav-item" id="appraisal">
                        <a class="nav-link disabled" href="#" role="button">
                        Appraisal 
                        </a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item" id="jump_bridges">
                        <a class="nav-link" href="{% url 'jump_bridges:manager' %}" role="button">
                        Admin 
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown my-auto mr-3">
                        <a class="nav-link dropdown-toggle py-0 mr-2" href="#" id="navbar_character_dropdown" role="button" data-toggle="dropdown">
                        <img src="https://image.eveonline.com/Character/1_32.jpg" height="32px" class="avatar mr-2" id="current_character_avatar"/>
                        <span class="align-middle" id="current_character_name"></span>
                        </a>
                        <div class="dropdown-menu" id="character_select_list">
                        </div>
                    </li>
                    <li class="nav-item my-auto mr-3">
                        <a class="nav-link" href="{% url 'eve_auth:logout' %}">
                        <i class="fas fa-sign-out-alt mr-1"></i> Log out
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item my-auto mr-3">
                        <a class="nav-link" href="{% url 'eve_auth:login' %}">
                        <i class="fas fa-sign-in-alt mr-1"></i> Log in
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main role="main">
            {% block content_container %}{% endblock %}
            <div style="height:75px;"></div>
        </main>
        <footer class="footer mt-auto">
            <div class="container">
                <span class="text-muted">
                Made by 
                <a class="text-info" href="https://evewho.com/character/2113697818">Aimsucks</a> • 
                <a class="text-info" href="https://discord.gg/UCK8ase">Discord</a> • 
                <a class="text-info" href="https://bitbucket.org/aimsucks/blue-donut/">Bitbucket</a>
                </span>
            </div>
        </footer>
        {{ eve_characters|json_script:'eve_characters' }}
        <script>
            var user_logged_in = {{ user.is_authenticated|yesno:"true,false" }};
        </script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/css/dataTables.bootstrap4.min.css"/>
        <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
        <script src="{% static 'js/character_switch.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/dataTables.bootstrap4.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js "></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>
        <script>
            $('.dropdown-accordion').on('show.bs.dropdown', function (event) {
                console.log("Yyoyoy")
                var accordion = $(this).find($(this).data('accordion'));
                accordion.find('.collapse').collapse('hide');
            });
            
            $('.dropdown-accordion').on('click', 'a[data-toggle="collapse"]', function (event) {
                console.log("1")
                event.preventDefault();
                event.stopPropagation();
                console.log("2")
                $($(this).data('parent')).find('.panel-collapse.in').collapse('hide');
                $($(this).attr('href')).collapse('show');
            })
        </script>
        {% block trailing_js %} {% endblock %}
    </body>
</html>

templates/content_page.html
{% extends 'base.html' %}

{% block content_container %}
{% block header %}{% endblock header %}

{% block content_tabs %}{% endblock content_tabs %}

<div class="container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
</div>

{% block content %}{% endblock content %}
{% endblock content_container %}